news/urls.py
from os import name
from django.urls import path
from django.conf.urls import url
from . import views
app_name = 'news'

urlpatterns = [
    path('', views.index, name='index'),
    url(r'^article/(?P<article_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^category/(?P<category_id>[0-9]+)/$', views.category, name='category'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),

]

schoolweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=150)

    class Meta:
        verbose_name_plural =   "categories"
    def __str__(self):
        return self.category_name


class Article(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    article_title = models.CharField(max_length=200)
    simple_heading = models.CharField(max_length=500)
    cover_photo = models.FileField()
    article_photo_1 = models.FileField()
    article_photo_2 = models.FileField()
    body = models.TextField(max_length=10000)
    Date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.article_title
        

news/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Article
from django.conf import settings


def index(request):
    all_categories = Category.objects.all()
    all_articles = reversed(Article.objects.all())
    latest_articles = Article.objects.all().order_by('-Date')[:3]
    context = {
        'all_categories': all_categories,
        'all_articles': all_articles,
        'latest_articles': latest_articles
    }
    return render(request, 'index.html', context)

def detail(request, article_id):
    articles = get_object_or_404(Article, pk=article_id)

    context = {
        'articles': articles
    }
    return render(request, 'pages/index-inner.html', context)
    

def category(request, category_id):
    categories = get_object_or_404(Category, pk=category_id)
    all_categories = Category.objects.all()

    context = {
        'categories': categories,
        'all_categories': all_categories
    }
    return render(request, 'pages/category.html', context)


def about(request):
    all_categories = Category.objects.all()
    context = {
        'all_categories': all_categories,
    }
    return render(request, 'pages/aboutus.html', context)


def contact(request):
    all_categories = Category.objects.all()
    context = {
        'all_categories': all_categories,
    }
    return render(request, 'pages/contactus.html', context)

news/templates/index.html
<!DOCTYPE html>
<html lang="en">
      {% load static %}
      {% load humanize %}
  <head>
    <!-- Required meta tags -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Kcu Newspaper</title>
    <!-- plugin css for this page -->
    <link
      rel="stylesheet"
      href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}"
    />
    <link rel="stylesheet" href="{% static 'assets/vendors/aos/dist/aos.css/aos.css' %}" />

    <!-- End plugin css for this page -->
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />

    <!-- inject:css -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <!-- endinject -->
  </head>

  <body>
    <div class="container-scroller">
      <div class="main-panel">
        <!-- partial:partials/_navbar.html -->
        <header id="header">
          <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light">
              
              <div class="navbar-bottom">
                <div class="d-flex justify-content-between align-items-center">
                  <div>
                    <a class="navbar-brand" href=""
                      ><img style="width: 80px; height: 60px" src="{% static 'assets/images/logo1.jpg' %}" alt=""
                    /></a>
                  </div>
                  <div>
                    <button
                      class="navbar-toggler"
                      type="button"
                      data-target="#navbarSupportedContent"
                      aria-controls="navbarSupportedContent"
                      aria-expanded="false"
                      aria-label="Toggle navigation"
                    >
                      <span class="navbar-toggler-icon"></span>
                    </button>
                    <div
                      class="navbar-collapse justify-content-center collapse"
                      id="navbarSupportedContent"
                    >
                      <ul
                        class="navbar-nav d-lg-flex justify-content-between align-items-center"
                      >
                        <li>
                          <button class="navbar-close">
                            <i class="mdi mdi-close"></i>
                          </button>
                        </li>
                        <li class="nav-item active">
                          <a class="nav-link" href="/">Home</a>
                        </li>
                        {% if all_categories  %}
                        {% for category in all_categories %}
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'news:category' category.id %}">{{ category.category_name }}</a>
                        </li>
                        {% endfor %}
                        {% else %}
                        <p></p>
                        {% endif %}
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'news:about' %}">About</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'news:contact' %}">Contact</a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </nav>
          </div>
        </header>

        <!-- partial -->
        
        <div class="content-wrapper">
          <div class="container">
            <div class="row" data-aos="fade-up">
              <div class="col-xl-8 stretch-card grid-margin">
                <div class="position-relative">
                  <img
                    src="{% static 'assets/images/dashboard/download (1).jpeg' %}"
                    style="width: 800px"
                    alt="banner"
                    class="img-fluid"
                  />
                  <div class="banner-content">
                    <div class="badge badge-danger fs-12 font-weight-bold mb-3">
                      Kcu news
                    </div>
                    <b><h1 class="mb-0"></h1></b>
                    <h1 class="mb-2" style="color: yellow">
                      <b>Your RealTime, Entertainment Website casting CampusLife </b>
                    </h1>
                  </div>
                </div>
              </div>
              <div class="col-xl-4 stretch-card grid-margin">
                <div class="card bg-dark text-white">
                  <div class="card-body">
                    <h2>Latest news</h2>

                    {% for latest in latest_articles %}
                    <a href="{% url 'news:detail' latest.id %}" style="color: white; text-decoration: none;">
                      <div
                        class="d-flex pt-4 align-items-center justify-content-between"
                      >
                        <div class="pr-3">
                          <h6>{{ latest.article_title }}</h6>
                          <div class="fs-12">
                            <span class="mr-2">By: {{ latest.author }} </span>{{ latest.Date|naturaltime }}
                          </div>
                        </div>
                        <div class="rotate-img">
                          <img
                            src="{{ latest.cover_photo.url }}"
                            alt="thumb"
                            style="height: 60px"
                            class="img-fluid img-lg"
                          />
                        </div>
                      </div>
                    </a>
                      {% endfor %}
                  </div>
                </div>
              </div>
            </div>
                <div class="card">
                  <div class="card-body">
                  {% for article in all_articles  %}
                    <a href="{% url 'news:detail' article.id %}" style="color: black; text-decoration: none;"> 
                    <div class="row">
                      <div class="col-sm-4 grid-margin">
                        <div class="position-relative">
                          
                            <div class="rotate-img">
                              <img
                                src="{{ article.cover_photo.url }}"
                                style="height: 240px; width: 100%"
                                alt="thumb"
                                class="img-fluid"
                              />
                            </div>
                            
                          <div class="badge-positioned">
                            <span class="badge badge-danger font-weight-bold"
                              >Kcu news</span
                            >
                          </div>
                        </div>
                      </div>
                      <div class="col-sm-8  grid-margin">
                        <h2 class="mb-2 font-weight-600">
                          {{ article.article_title }}
                        </h2>
                        <div class="fs-13 mb-2">
                          <span class="mr-2">By: {{ article.author }} </span>{{ article.Date }}
                        </div>
                        <p class="mb-0">
                          {{ article.simple_heading }}
                        </p>
                      </div>
                    </div>
                    </a>
                    <br>
                    {% endfor %}

                    <br>

                  </div>
                </div>
          </div>
        </div>
        <!-- main-panel ends -->
        <!-- container-scroller ends -->

        <!-- partial:partials/_footer.html -->
        <footer>
          <div class="footer-top">
            <div class="container">
              <div class="row">
                <div class="col-sm-5">
                  <img src="assets/images/logo.svg" class="footer-logo" alt="" />
                  <h5 class="font-weight-normal mt-4 mb-5">
                    KCUNEWS is your RealTime, entertainment, music fashion website. We
                    provide you with the latest breaking news and videos straight from
                    the entertainment industry.
                  </h5>
                  <ul class="social-media mb-3">
                    <li>
                      <a href="https://www.facebook.com/ntwali.andrew">
                        <i class="mdi mdi-facebook"></i>
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <i class="mdi mdi-youtube"></i>
                      </a>
                    </li>
                    <li>
                      <a href="https://www.twitter.com/ntwaliandrew3">
                        <i class="mdi mdi-twitter"></i>
                      </a>
                    </li>
                  </ul>
                </div>
                
                
              </div>
            </div>
          </div>
          <div class="footer-bottom">
            <div class="container">
              <div class="row">
                <div class="col-sm-12">
                  <div class="d-sm-flex justify-content-between align-items-center">
                    <div class="fs-14 font-weight-600">
                      © 2020 @ <a href="https://www.twitter.com/ntwaliandrew3" target="_blank" class="text-white"> AndySolutions</a>. All rights reserved.
                    </div>
                    <div class="fs-14 font-weight-600">
                      Handcrafted by <a href="https://www.twitter.com/ntwaliandrew3" target="_blank" class="text-white">Andy250</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </footer>

        <!-- partial -->
      </div>
    </div>
    <!-- inject:js -->
    <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- plugin js for this page -->
    <script src="{% static 'assets/vendors/aos/dist/aos.js/aos.js' %}"></script>
    <!-- End plugin js for this page -->
    <!-- Custom js for this page-->
    <script src="{% static 'assets/js/demo.js' %}"></script>
    <script src="{% static 'assets/js/jquery.easeScroll.js' %}"></script>
    <!-- End custom js for this page-->
  </body>
</html>

news/templates/pages/aboutus.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Kcu Newspaper</title>
    <!-- plugin css for this page -->
    <link
      rel="stylesheet"
      href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}"
    />
    <link rel="stylesheet" href="{% static 'assets/vendors/aos/dist/aos.css/aos.css' %}" />

    <!-- End plugin css for this page -->
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />

    <!-- inject:css -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <!-- endinject -->
  </head>

  <body>
    <div class="container-scroller">
      <div class="main-panel">
        <!-- partial:partials/_navbar.html -->
        <header id="header">
          <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light">
              
              <div class="navbar-bottom">
                <div class="d-flex justify-content-between align-items-center">
                  <div>
                    <a class="navbar-brand" href=""
                      ><img style="width: 80px; height: 60px" src="{% static 'assets/images/logo1.jpg' %}" alt=""
                    /></a>
                  </div>
                  <div>
                    <button
                      class="navbar-toggler"
                      type="button"
                      data-target="#navbarSupportedContent"
                      aria-controls="navbarSupportedContent"
                      aria-expanded="false"
                      aria-label="Toggle navigation"
                    >
                      <span class="navbar-toggler-icon"></span>
                    </button>
                    <div
                      class="navbar-collapse justify-content-center collapse"
                      id="navbarSupportedContent"
                    >
                      <ul
                        class="navbar-nav d-lg-flex justify-content-between align-items-center"
                      >
                        <li>
                          <button class="navbar-close">
                            <i class="mdi mdi-close"></i>
                          </button>
                        </li>
                        <li class="nav-item active">
                          <a class="nav-link" href="/">Home</a>
                        </li>
                        {% if all_categories  %}
                        {% for category in all_categories %}
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'news:category' category.id %}">{{ category.category_name }}</a>
                        </li>
                        {% endfor %}
                        {% else %}
                        <p></p>
                        {% endif %}
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'news:about' %}">About</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'news:contact' %}">Contact</a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </nav>
          </div>
        </header>

      <div class="content-wrapper">
        <div class="container">
          <div class="row">
            <div class="col-sm-12">
              <div class="card" data-aos="fade-up">
                <div class="card-body">
                  <div class="aboutus-wrapper">
                    <h1 class="mt-5">
                      About Us
                    </h1>
                    <p class="font-weight-600 fs-15">
                      This is a campus website mainly used for broadcasting CampusLife and what happens around
                      helping students to be updated on some news and information around campus.
                      We create standard articles basing on realtime effect.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- container-scroller ends -->
    <!-- partial:../partials/_footer.html -->
    <footer>
          <div class="footer-top">
            <div class="container">
              <div class="row">
                <div class="col-sm-5">
                  <img src="assets/images/logo.svg" class="footer-logo" alt="" />
                  <h5 class="font-weight-normal mt-4 mb-5">
                    KCUNEWS is your RealTime, entertainment, music fashion website. We
                    provide you with the latest breaking news and videos straight from
                    the entertainment industry.
                  </h5>
                  <ul class="social-media mb-3">
                    <li>
                      <a href="https://www.facebook.com/ntwali.andrew">
                        <i class="mdi mdi-facebook"></i>
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <i class="mdi mdi-youtube"></i>
                      </a>
                    </li>
                    <li>
                      <a href="https://www.twitter.com/ntwaliandrew3">
                        <i class="mdi mdi-twitter"></i>
                      </a>
                    </li>
                  </ul>
                </div>
                
                
              </div>
            </div>
          </div>
          <div class="footer-bottom">
            <div class="container">
              <div class="row">
                <div class="col-sm-12">
                  <div class="d-sm-flex justify-content-between align-items-center">
                    <div class="fs-14 font-weight-600">
                      © 2020 @ <a href="https://www.twitter.com/ntwaliandrew3" target="_blank" class="text-white"> AndySolutions</a>. All rights reserved.
                    </div>
                    <div class="fs-14 font-weight-600">
                      Handcrafted by <a href="https://www.twitter.com/ntwaliandrew3" target="_blank" class="text-white">Andy250</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </footer>

    <!-- partial -->
    <!-- inject:js -->
    <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- plugin js for this page -->
    <script src="{% static 'assets/vendors/aos/dist/aos.js/aos.js' %}"></script>
    <!-- End plugin js for this page -->
    <!-- Custom js for this page-->
    <script src="{% static 'assets/js/demo.js' %}"></script>
    <script src="{% static 'assets/js/jquery.easeScroll.js' %}"></script>
    <!-- End custom js for this page-->
  </body>
</html>

news/templates/pages/category.html
<!DOCTYPE html>
<html lang="zxx">
  {% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Kcu Newspaper</title>
    <!-- plugin css for this page -->
    <link
      rel="stylesheet"
      href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}"
    />
    <link rel="stylesheet" href="{% static 'assets/vendors/aos/dist/aos.css/aos.css' %}" />

    <!-- End plugin css for this page -->
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />

    <!-- inject:css -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <!-- endinject -->
  </head>

  <body>
    <div class="container-scroller">
      <div class="main-panel">
        <!-- partial:../partials/_navbar.html -->
        <header id="header">
          <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light">
              
              <div class="navbar-bottom">
                <div class="d-flex justify-content-between align-items-center">
                  <div>
                    <a class="navbar-brand" href="/"
                      ><img style="width: 80px; height: 60px" src="{% static 'assets/images/logo1.jpg' %}" alt=""
                    /></a>
                  </div>
                  <div>
                    <button
                      class="navbar-toggler"
                      type="button"
                      data-target="#navbarSupportedContent"
                      aria-controls="navbarSupportedContent"
                      aria-expanded="false"
                      aria-label="Toggle navigation"
                    >
                      <span class="navbar-toggler-icon"></span>
                    </button>
                    <div
                      class="navbar-collapse justify-content-center collapse"
                      id="navbarSupportedContent"
                    >
                      <ul
                        class="navbar-nav d-lg-flex justify-content-between align-items-center"
                      >
                        <li>
                          <button class="navbar-close">
                            <i class="mdi mdi-close"></i>
                          </button>
                        </li>
                        <li class="nav-item active">
                          <a class="nav-link" href="/">Home</a>
                        </li>
                        {% if all_categories  %}
                        {% for category in all_categories %}
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'news:category' category.id %}">{{ category.category_name }}</a>
                        </li>
                        {% endfor %}
                        {% else %}
                        <p></p>
                        {% endif %}
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'news:about' %}">About</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'news:contact' %}">Contact</a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </nav>
          </div>
        </header>

        <div class="content-wrapper">
          <div class="container">
            <div class="col-sm-12">
              <div class="card" data-aos="fade-up">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-12">
                      <h1 style="text-align: center;" class="font-weight-600 mb-4">
                        {{categories.category_name}} News
                      </h1>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-8">
                    
                    
                      {% for article in categories.article_set.all %}
                      <a href="{% url 'news:detail' article.id %}" style="color: black; text-decoration: none;"> 
                        <div class="row">
                          <div class="col-sm-4 grid-margin">
                            <div class="rotate-img">
                              <img
                                src="{{ article.cover_photo.url }}"
                                style="height: 240px; width: 100%"
                                alt="banner"
                                class="img-fluid"
                              />
                            </div>
                          </div>
                          <div class="col-sm-8 grid-margin">
                            <h2 class="font-weight-600 mb-2">
                              {{ article.article_title }}
                            </h2>
                            <p class="fs-13 text-muted mb-0">
                              <span class="mr-2">By: {{ article.author }} </span>{{ article.Date }}
                            </p>
                            <p class="fs-15">
                              {{ article.simple_heading }}
                            </p>
                          </div>
                        </div>
                      </a>
                      {% endfor %}

                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- main-panel ends -->
        <!-- container-scroller ends -->

        <!-- partial:../partials/_footer.html -->
        <footer>
          <div class="footer-top">
            <div class="container">
              <div class="row">
                <div class="col-sm-5">
                  <img src="assets/images/logo.svg" class="footer-logo" alt="" />
                  <h5 class="font-weight-normal mt-4 mb-5">
                    KCUNEWS is your RealTime, entertainment, music fashion website. We
                    provide you with the latest breaking news and videos straight from
                    the entertainment industry.
                  </h5>
                  <ul class="social-media mb-3">
                    <li>
                      <a href="https://www.facebook.com/ntwali.andrew">
                        <i class="mdi mdi-facebook"></i>
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <i class="mdi mdi-youtube"></i>
                      </a>
                    </li>
                    <li>
                      <a href="https://www.twitter.com/ntwaliandrew3">
                        <i class="mdi mdi-twitter"></i>
                      </a>
                    </li>
                  </ul>
                </div>
                
                
              </div>
            </div>
          </div>
          <div class="footer-bottom">
            <div class="container">
              <div class="row">
                <div class="col-sm-12">
                  <div class="d-sm-flex justify-content-between align-items-center">
                    <div class="fs-14 font-weight-600">
                      © 2020 @ <a href="https://www.twitter.com/ntwaliandrew3" target="_blank" class="text-white"> AndySolutions</a>. All rights reserved.
                    </div>
                    <div class="fs-14 font-weight-600">
                      Handcrafted by <a href="https://www.twitter.com/ntwaliandrew3" target="_blank" class="text-white">Andy250</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </footer>

        <!-- partial -->
      </div>
    </div>

    <!-- inject:js -->
    <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- plugin js for this page -->
    <script src="{% static 'assets/vendors/aos/dist/aos.js/aos.js' %}"></script>
    <!-- End plugin js for this page -->
    <!-- Custom js for this page-->
    <script src="{% static 'assets/js/demo.js' %}"></script>
    <script src="{% static 'assets/js/jquery.easeScroll.js' %}"></script>
    <!-- End custom js for this page-->
  </body>
</html>